# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c9dc178bf7636e872332326cd98606135de2a7116d93c66a885da7e3b1663f04a7b392a8af53b7e163c9116860a2ae042cc3710b4f4ddef54669c8388f20799

test:
  secret_key_base: f49e91961ac44861c2553f8ca4e97e865efdafacee593ff902b20452d2ca558e35bdd825558e25a34af8a20ca8faadab15a1ad656619d333e487997a89813c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
